IZE-113 infra lock
hazelops/tflock pull request #1
Opened 2022-03-02 10:35 UTC by psihachina

## Changelog:
- add dynamodb package
- add cli app
- update README

## Test:
[![asciicast](https://asciinema.org/a/mgWnWYzm6mygx37idxJwYGdhE.svg)](https://asciinema.org/a/mgWnWYzm6mygx37idxJwYGdhE)

2022-03-02 10:46 UTC, kobrikx approved these changes
LGTM

2022-03-02 10:48 UTC, AutomationD requested changes

2022-03-02 10:48 UTC, AutomationD commented on README.md
> +Until support only S3 backend.
```suggestion
Only S3 backend is supported for now.
```

2022-03-02 10:48 UTC, AutomationD commented on README.md
> +## Install
```suggestion
## Building
```

2022-03-02 10:48 UTC, AutomationD commented on main.go
> +				Usage:       "lock id",
```suggestion
				Usage:       "specify lock id, usually just a path to the state file in your s3 bucket",
```

2022-03-02 10:48 UTC, DimmKirr commented on main.go
> +				Name:        "aws region",
```suggestion
				Name:        "aws-region",
```

2022-03-02 10:48 UTC, DimmKirr commented on main.go
> +			},
Let's add `dynamodb-table` parameter please

2022-03-02 10:48 UTC, AutomationD commented on dynamodb/dynamodb.go
> +	tableName := "tf-state-lock"
Let's parametrize this please.

2022-03-03 06:47 UTC, igorkotof approved these changes

2022-03-04 08:19 UTC, AutomationD reviewed
Looks good!

2022-03-04 08:19 UTC, AutomationD approved these changes
Looks good!

2022-03-07 08:01 UTC, merged